package bankApp;


/**
* bankApp/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Bank.idl
* dimanche 4 décembre 2016 15 h 44 CET
*/

public interface AccountOperations 
{
  void deposit (int amount);
  void withdraw (int amount) throws bankApp.insufficientFunds;
  bankApp.AccountDetails details ();
  int balance ();
  void initTransfer (org.omg.CORBA.Any to, int ammount);
} // interface AccountOperations
