package bankApp;

/**
* bankApp/BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Bank.idl
* dimanche 4 décembre 2016 15 h 44 CET
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public bankApp.Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (bankApp.Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankApp.BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankApp.BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankApp.BankHelper.type ();
  }

}
