package bankApp;


/**
* bankApp/InterbankPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Bank.idl
* dimanche 4 décembre 2016 15 h 44 CET
*/

public abstract class InterbankPOA extends org.omg.PortableServer.Servant
 implements bankApp.InterbankOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("transfer", new java.lang.Integer (0));
    _methods.put ("put", new java.lang.Integer (1));
    _methods.put ("get", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // bankApp/Interbank/transfer
       {
         bankApp.Transfer transaction = bankApp.TransferHelper.read (in);
         this.transfer (transaction);
         out = $rh.createReply();
         break;
       }

       case 1:  // bankApp/Interbank/put
       {
         bankApp.Transfer transaction = bankApp.TransferHelper.read (in);
         this.put (transaction);
         out = $rh.createReply();
         break;
       }

       case 2:  // bankApp/Interbank/get
       {
         org.omg.CORBA.Any reference = in.read_any ();
         org.omg.CORBA.Any $result = null;
         $result = this.get (reference);
         out = $rh.createReply();
         out.write_any ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:bankApp/Interbank:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Interbank _this() 
  {
    return InterbankHelper.narrow(
    super._this_object());
  }

  public Interbank _this(org.omg.CORBA.ORB orb) 
  {
    return InterbankHelper.narrow(
    super._this_object(orb));
  }


} // class InterbankPOA
