package bankApp;


/**
* bankApp/InterbankOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Bank.idl
* dimanche 4 décembre 2016 15 h 44 CET
*/

public interface InterbankOperations 
{
  void transfer (bankApp.Transfer transaction);
  void put (bankApp.Transfer transaction);
  org.omg.CORBA.Any get (org.omg.CORBA.Any reference);
} // interface InterbankOperations
