package bankApp;

/**
* bankApp/TransferHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Bank.idl
* dimanche 4 décembre 2016 15 h 44 CET
*/

public final class TransferHolder implements org.omg.CORBA.portable.Streamable
{
  public bankApp.Transfer value = null;

  public TransferHolder ()
  {
  }

  public TransferHolder (bankApp.Transfer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankApp.TransferHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankApp.TransferHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankApp.TransferHelper.type ();
  }

}
