package bankApp;


/**
* bankApp/AccountDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* dimanche 4 décembre 2016 16 h 11 CET
*/

public final class AccountDetails implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String address[] = null;
  public int account_number = (int)0;
  public double current_balance = (double)0;

  public AccountDetails ()
  {
  } // ctor

  public AccountDetails (String _name, String[] _address, int _account_number, double _current_balance)
  {
    name = _name;
    address = _address;
    account_number = _account_number;
    current_balance = _current_balance;
  } // ctor

} // class AccountDetails
