package bankApp;

/**
* bankApp/AccountDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* dimanche 4 décembre 2016 16 h 11 CET
*/

public final class AccountDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public bankApp.AccountDetails value = null;

  public AccountDetailsHolder ()
  {
  }

  public AccountDetailsHolder (bankApp.AccountDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankApp.AccountDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankApp.AccountDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankApp.AccountDetailsHelper.type ();
  }

}
