package bankApp;


/**
* bankApp/insufficientFunds.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* dimanche 4 décembre 2016 16 h 11 CET
*/

public final class insufficientFunds extends org.omg.CORBA.UserException
{

  public insufficientFunds ()
  {
    super(insufficientFundsHelper.id());
  } // ctor


  public insufficientFunds (String $reason)
  {
    super(insufficientFundsHelper.id() + "  " + $reason);
  } // ctor

} // class insufficientFunds
