package bankApp;


/**
* bankApp/TransferHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* dimanche 4 décembre 2016 16 h 11 CET
*/

abstract public class TransferHelper
{
  private static String  _id = "IDL:bankApp/Transfer:1.0";

  public static void insert (org.omg.CORBA.Any a, bankApp.Transfer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static bankApp.Transfer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = bankApp.AccountHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "to",
            _tcOf_members0,
            null);
          _tcOf_members0 = bankApp.AccountHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "from",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[2] = new org.omg.CORBA.StructMember (
            "sum",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (bankApp.TransferHelper.id (), "Transfer", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static bankApp.Transfer read (org.omg.CORBA.portable.InputStream istream)
  {
    bankApp.Transfer value = new bankApp.Transfer ();
    value.to = bankApp.AccountHelper.read (istream);
    value.from = bankApp.AccountHelper.read (istream);
    value.sum = istream.read_ulong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, bankApp.Transfer value)
  {
    bankApp.AccountHelper.write (ostream, value.to);
    bankApp.AccountHelper.write (ostream, value.from);
    ostream.write_ulong (value.sum);
  }

}
