
/**
* Echo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* mardi 15 novembre 2016 15 h 50 CET
*/

public interface Echo extends EchoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Echo
