
/**
* EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* mardi 15 novembre 2016 15 h 50 CET
*/

public interface EchoOperations 
{
  String echoString (String mesg);
} // interface EchoOperations
